export enum ErrorCodesEnum {
  CLIENT_CREATE_FAILED = 'CLIENT_CREATE_FAILED',
  CLIENT_GET_BY_ID_FAILED = 'CLIENT_GET_BY_ID_FAILED',
  CLIENT_GET_BY_NAME_FAILED = 'CLIENT_GET_BY_NAME_FAILED',
  CLIENT_UPDATE_FAILED = 'CLIENT_UPDATE_FAILED',
  CLIENT_DELETE_FAILED = 'CLIENT_DELETE_FAILED',

  SCOPE_CREATE_FAILED = 'SCOPE_CREATE_FAILED',
  SCOPE_GET_BY_ID_FAILED = 'SCOPE_GET_BY_ID_FAILED',
  SCOPE_GET_BY_API_NAME_FAILED = 'SCOPE_GET_BY_API_NAME_FAILED',
  SCOPE_UPDATE_FAILED = 'SCOPE_UPDATE_FAILED',
  SCOPE_DELETE_FAILED = 'SCOPE_DELETE_FAILED',

  SCHEMA_VALIDATION_FAILED = 'schema_validation_failed',
}
