Resources:
  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 300
      AuthorizerUri:
        Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - ${opt:region, 'us-east-1'}
            - ':lambda:path/2015-03-31/functions/'
            - ${self:custom.config.authorizer.${opt:region, 'us-east-1'}.arn}
            - '/invocations'
      Type: 'TOKEN'
      IdentitySource: 'method.request.header.Authorization'
      IdentityValidationExpression: .+
      Name: Authorizer
      RestApiId:
        Ref: ApiGatewayRestApi
  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: ${self:custom.config.authorizer.${opt:region, 'us-east-1'}.arn}
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: 
        Fn::Join:
          - ''
          - - 'arn:aws:execute-api:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':'
            - Ref: ApiGatewayRestApi
            - '/*'